Repository juju/terraform-provider-juju, pull requests merged in 2023-07, with the labels that each got.

#234 [JUJU-4010] Github action for add machine integration test
  .github/workflows/test_add_machine.yml
Labels: github_actions

#238 [JUJU-4186] Use also the Terraform 1.5 for integration tests
  .github/workflows/test_add_machine.yml
  .github/workflows/test_integration.yml
  .github/workflows/test_new_candidates.yml
Labels: maintenance

#240 [JUJU-4170] Create mux terraform framework
  docs/data-sources/machine.md
  docs/data-sources/model.md
  docs/data-sources/offer.md
  docs/resources/user.md
  go.mod
  go.sum
  internal/provider/provider.go
  internal/provider/provider_test.go
  main.go
Labels: maintenance

#241 Additional make target: docs
  Makefile
Labels: maintenance

#242 [JUJU-4179] Create model data source in framework
  go.mod
  go.sum
  internal/provider/data_source_machine_test.go
  internal/provider/data_source_model.go
  internal/provider/data_source_model_test.go
  internal/provider/data_source_offer_test.go
  internal/provider/provider.go
  internal/provider/resource_access_model_test.go
  internal/provider/resource_application_test.go
  internal/provider/resource_credential_test.go
  internal/provider/resource_integration_test.go
  internal/provider/resource_machine_test.go
  internal/provider/resource_model_test.go
  internal/provider/resource_offer_test.go
  internal/provider/resource_ssh_key_test.go
  internal/provider/resource_user_test.go
  main.go
Labels: maintenance

#250 [JUJU-4342] Upgrade provider server protocol v5 to v6
  internal/provider/data_source_machine_test.go
  internal/provider/data_source_model_test.go
  internal/provider/data_source_offer_test.go
  internal/provider/provider_test.go
  internal/provider/resource_access_model_test.go
  internal/provider/resource_application_test.go
  internal/provider/resource_credential_test.go
  internal/provider/resource_integration_test.go
  internal/provider/resource_machine_test.go
  internal/provider/resource_model_test.go
  internal/provider/resource_offer_test.go
  internal/provider/resource_ssh_key_test.go
  internal/provider/resource_user_test.go
  internal/provider/test-add-machine
  internal/provider/test-add-machine.pub
  main.go
  terraform-registry-manifest.json
Labels: maintenance, donotmerge

#246 [JUJU-4182] Create user resource in framework
  docs/resources/user.md
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_access_model_test.go
  internal/provider/resource_user.go
  internal/provider/resource_user_test.go
Labels: maintenance
