Repository juju/terraform-provider-juju, pull requests merged in 2024-07, with the labels that each got.

#515 test: parallelize tests
  .github/workflows/test_integration.yml
  Makefile
  internal/provider/data_source_machine_test.go
  internal/provider/data_source_model_test.go
  internal/provider/data_source_offer_test.go
  internal/provider/data_source_secrets_test.go
  internal/provider/main_test.go
  internal/provider/provider_test.go
  internal/provider/resource_access_model_test.go
  internal/provider/resource_access_secret_test.go
  internal/provider/resource_application_test.go
  internal/provider/resource_credential_test.go
  internal/provider/resource_integration_test.go
  internal/provider/resource_machine_test.go
  internal/provider/resource_model_test.go
  internal/provider/resource_offer_test.go
  internal/provider/resource_secret_test.go
  internal/provider/resource_ssh_key_test.go
  internal/provider/resource_user_test.go
Labels: hint/do-not-merge

#527 chore(release): update changelogs for 0.13.0-rc2 release
  CHANGELOG.md
Labels: kind/release-changelog

#529 fix(github): fix goreleaser configuration to comply with version 2
  .goreleaser.yml
Labels: area/maintenance
